name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - review_requested
      - closed
jobs:
  issue_opened_and_reopened:
    name: Issue Opened/Reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: 'Move issue to "Pending"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.2
        with:
          gh_token: ${{ secrets.AUTOMATION_SECRET }}
          organization: WhiteBox-Systems
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Pending"
  issue_closed:
    name: Issue Closed
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: 'Moved issue to "Done"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.2
        with:
          gh_token: ${{ secrets.AUTOMATION_SECRET }}
          organization: WhiteBox-Systems
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Done"
