# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects

name: Add PR to project
on: [issues, pull_request]
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to project
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_SECRET }}
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $pr}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f pr=$PR_ID --jq '.data.addProjectNextItem.projectNextItem.id')"
          
          echo 'ITEM_ID='$item_id >> $GITHUB_ENV
